dataset:
  dataset_name: 'Wafer'
  in_channels: 1
  data_scaling: True
  num_workers: 0

stage1:
  batch_size: 128
  max_epochs: 1000
  lr: 0.001
  weight_decay: 0.00001
  gpus: 0

stage2:
  batch_size: 128
  max_epochs: 1000
  lr: 0.001
  weight_decay: 0.00001
  gpus: 0

stage3:
  n_samples: 100
  sampling_steps:
    lf: 10
    hf: 50
  class_index: None
  batch_size: 128

EncDec:
  dim: 4
  n_resnet_blocks: 4
  downsampled_width:
    lf: 8
    hf: 32

VQ:
  n_fft: 8
  codebook_dim: 4
  codebook_sizes:
    lf: 512
    hf: 512
  decay: 0.8
  commitment_weight: 1.
  emb_dropout: 0.
  perceptual_loss_weight: 0

Unet:
  dim: 64
  dim_mults:
    lf: (1,2)
    hf: (1,2,4,8)
  resnet_block_groups: 4
  class_dim: 128
  time_dim: 128

VDM:
  objective: pred_noise
  loss_type: l2
  lr: 0.00001
  adam_betas:
    - 0.9
    - 0.99
  p_unconditional: 0.1