dataset:
  dataset_name: 'Wafer'
  in_channels: 1
  data_scaling: True
  batch_sizes:
    stage1: 128
    stage2: 256
  num_workers: 0

exp_params:
  lr: 0.001
  weight_decay: 0.00001

trainer_params:
  gpus:
    - 0
  max_epochs:
    stage1: 200
    stage2: 500


encoder:
  dim: 64
  n_resnet_blocks: 4
  downsampled_width:
    lf: 8
    hf: 32

decoder:
  dim: 64
  n_resnet_blocks: 4


VQ-VAE:
  n_fft: 8
  codebook_sizes:
    lf: 32
    hf: 32
  decay: 0.8
  commitment_weight: 1.
  codebook_dim: 64
  emb_dropout: 0.
  perceptual_loss_weight: 0

Unet:
    dim: 64
    dim_mults: (1,2,4,8)
    in_channels: 1
    resnet_block_groups: 8
    class_dim: 128
    time_dim: 128

VDM:
  objective: pred_noise
  loss_type: l2
  lr: 0.00001
  adam_betas:
    - 0.9
    - 0.99
  p_unconditional: 0.1

class_guidance:
  guidance_scale: 1.